name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  flake-check:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Cachix (optional)
        if: ${{ vars.CACHIX_CACHE_NAME != '' && secrets.CACHIX_AUTH_TOKEN != '' }}
        uses: cachix/cachix-action@v14
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: nix flake check
        run: nix flake check --print-build-logs --show-trace
